name: Release
on:
  push:
    branches:
      - main
    tags:
      - "v*"
jobs:
  release:
    name: Release
    runs-on: windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Install Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Update version.txt versionNum
        run: |
          python .\resources\versionInfo.py ${{ steps.get_version.outputs.VERSION }}

      - name: Build
        run: |
          python .\resources\build.py

      - name: Upload .exe files from dist
        uses: actions/upload-artifact@v3
        with:
          path: dist/*.exe # 匹配 dist 目录下所有 .exe 文件

