name: Release
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
jobs:
  release:
    name: Release
    runs-on: windows-latest
    steps:

    - name: Get the tag version
      id: get_tag
      run: echo "VERSION_NUM=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

    - name: Install Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Ensure version.txt exists and update versionNum
      run: |
          $versionFilePath = "$PWD/version.txt"  # 使用仓库根目录的路径
             
          # 格式化版本号
          $VERSION_NUM = "${env:VERSION_NUM}"
          $versionNumFormatted = $VERSION_NUM -replace '\.', ', '
          $versionStringFormatted = $VERSION_NUM -replace ',', '.'
          
          # 替换文件中的内容
          (Get-Content $versionFilePath) -replace "versionNum = .+", "versionNum = $versionNumFormatted" | Set-Content $versionFilePath
          (Get-Content $versionFilePath) -replace "versionString = .+", "versionString = $versionStringFormatted" | Set-Content $versionFilePath
          Get-Content $versionFilePath
    
       
    
    