name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: Release
    runs-on: windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3


      - name: Install Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Update version.txt versionNum
        run: |
          python .\resources\versionInfo.py ${{ github.ref }}

      - name: Build
        run: |
          uv run pyinstaller .\build.spec  

      - name: Upload .exe files from dist
        uses: actions/upload-artifact@v3
        with:
          path: dist/*.exe # 匹配 dist 目录下所有 .exe 文件

